sudo: false

language: node_js

node_js:
  - "node" # the latest stable nodejs

notifications:
  email: false

env:
  matrix:
    - CI_MATRIX_BUILD=true
    - CI_MATRIX_LINT=true
    - CI_MATRIX_TEST=true

script:
  - |
    if [ "$CI_MATRIX_BUILD" = "true" ]; then
      npm run build
    elif [ "$CI_MATRIX_LINT" = "true" ]; then
      npm run lint
    elif [ "$CI_MATRIX_TEST" = "true" ]; then
      npm run build
      npm run test
    else
      echo "This code path is run unexpectedly" 1>&2
      exit 1
    fi
